title = "Gitleaks Configuration"
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key\s*=\s*['"][0-9a-zA-Z]{32,45}['"])'''
tags = ["apikey"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)(aws[_-]?secret[_-]?access[_-]?key\s*=\s*['"][0-9a-zA-Z/+]{40}['"])'''
tags = ["aws", "apikey"]
